sudo: required

language: clojure

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "SlN01tXsLYzorjfiGqRhmn1IMKCJjGDFnzsizJy/JV4OoXE2BDUoo8TyjgXgjcZJYozJbdeE+UPs9xYummGpUwtKeDlN81wKSOk2NsHnAOtesSUxMoJSjqbZCYph2HofN8zzq5Wedof1NJtPqklh5lsT+um7ipRFxIhZ1YN8kAE="
    # AWS_SECRET_ACCESS_KEY
    - secure: "uomqrG3zytYEinGRzYuF3lNpfzLdnuXHUdbtP+KidejHrFvwKMu4TCTmTBUVet6Nb3xakPupP793O53Q/UW+ZhuOQ63FrOh9RLBEb7AMl0D7u+lSDay32Udlnwdu2U/J4Yn2u6VLSsiAG2JAf88H9vWXveOTVldKqH3jEe4BdzU="

before_install:
  - nvm install 8.9.4

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git --branch PP-357_458_readonly_container_nonroot_user
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="osaan"

script:
  # clojure-utils
  - git submodule init
  - git submodule update

  - ./dev-scripts/build.sh

  - mv app/target/${ARTIFACT_NAME}-standalone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - mv db/target/${ARTIFACT_NAME}-db-standalone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-db.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/
  - cp -vr app/resources ${DOCKER_BUILD_DIR}/config/

  - export BASE_IMAGE="baseimage-fatjar:ci-119"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh ${ARTIFACT_NAME}

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
  on:
    all_branches: true
