// Copyright (c) 2015 The Finnish National Board of Education - Opetushallitus
//
// This program is free software:  Licensed under the EUPL, Version 1.1 or - as
// soon as they will be approved by the European Commission - subsequent versions
// of the EUPL (the "Licence");
//
// You may not use this work except in compliance with the Licence.
// You may obtain a copy of the Licence at: http://www.osor.eu/eupl/
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// European Union Public Licence for more details.

'use strict';

angular.module('osaan.tekstit', ['pascalprecht.translate'])
  .constant('tekstit', {
    fi: {
      'arviointi.arvioi_osaamisesi': 'Arvioi osaamisesi',
      'arviointi.arvioita_puuttuu': 'Et ole antanut arvioita kaikista ammattitaidoista!',
      'arviointi.asteikko1': 'En osaa',
      'arviointi.asteikko2': 'Osaan vähän',
      'arviointi.asteikko3': 'Osaan hyvin',
      'arviointi.asteikko4': 'Osaan erinomaisesti',
      'arviointi.eos': 'En osaa sanoa',
      'arviointi.raportti': 'Näytä raportti',
      'arviointi.tekstivastaus': 'Tekstivastaus',
      'arviointi.tekstivastaus_placeholder': 'Kirjoita vastauksesi tähän',
      'arviointi.valitse_osa': 'Valitse tutkinnon osat',
      'etusivu.opintoala': 'Ala',
      'etusivu.otsikko': 'Osaamisen tunnistaminen',
      'etusivu.teksti': 'Voit arvioida osaamistasi valitsemassasi ammatissa. Arviointi tehdään tutkinnoissa edellytettyjen ammattitaitovaatimusten perusteella, jotka on laadittu yhteistyössä työelämän kanssa. Tutkinnon suorittamisessa huomioidaan aiempi osaamisesi, joka voi olla hankittu esimerkiksi työssä, opinnoissa tai muussa toiminnassa. Kun hakeudut suorittamaan tutkintoa, koulutuksen järjestäjä selvittää aiemman osaamisen kanssasi.\n\nValitse tutkinto ja sen jälkeen ne tutkinnon osat, jotka haluaisit suorittaa. Sen jälkeen vastaa väittämiin. Saat vastauksista raportin, jonka voit tulostaa tai tallentaa. Henkilötietoja ei kysytä, raportti yksilöidään satunnaisella koodilla. Jos olet kiinnostunut suorittamaan ammatillisen perustutkinnon, ammattitutkinnon tai erikoisammattitutkinnon, ole yhteydessä näyttötutkinnon tai koulutuksen järjestäjiin, jotka näet linkkien kautta.',
      'etusivu.tutkinnon_nimi': 'Tutkinnon nimi',
      'etusivu.tutkinnon_nimi_placeholder': 'Kirjoita tutkinnon nimi tai nimen osa',
      'footer.ota_yhteytta': 'osaan.fi käyttöä koskevan palautteen voi lähettää sähköpostilla osoitteeseen',
      'footer.ota_yhteytta_email': 'aitu-tuki@oph.fi',
      'footer.otsikko': 'Palvelun tarjoaa Opetushallitus',
      'footer.rekisteriseloste': 'osaan.fi rekisteriselosteen voit lukea osoitteesta:',
      'footer.rekisteriseloste_url': 'http://osaan.fi/Rekisteriseloste%20Osaan%20fi.pdf',
      'lataa.palaa_etusivulle': 'Palaa etusivulle',
      'lataa.virhe': 'Virheellinen latauslinkki.',
      'osien-valinta.arvio_ladattu': '{{luotuaika}} luotu arviointisi on nyt ladattu. Voit jatkaa arviointiasi ja tallentaa uuden arvion.',
      'osien-valinta.arvio_ladattu_otsikko': 'Arvio on ladattu',
      'osien-valinta.arvioita_on': 'Valituille osille löytyy arvioita',
      'osien-valinta.eteenpain': 'Eteenpäin',
      'osien-valinta.pakolliset_osat': 'Pakolliset osat',
      'osien-valinta.poista_arviot': 'Poista arviot',
      'osien-valinta.poista_arviot_otsikko': 'Haluatko varmasti poistaa jo annetut arviot?',
      'osien-valinta.poista_arviot_varoitus': 'Arvioita ei voi palauttaa.',
      'osien-valinta.poisto-teksti': 'Jos haluat arvoida näiden osien osaamisesi uudestaan voit poistaa aiemmat arviosi',
      'osien-valinta.valinnaiset_osat': 'Valinnaiset osat',
      'osien-valinta.yhteiset_osat': 'Yhteiset osat',
      'polku.arvioi_osaaminen': 'Arvioi osaaminen',
      'polku.raportti': 'Raportti',
      'polku.valitse_tutkinnon_osat': 'Valitse tutkinnon osat',
      'polku.valitse_tutkinto': 'Valitse tutkinto',
      'raportti.ammattitaidon_kuvaus': 'Ammattitaidon kuvaus',
      'raportti.arvio': 'Arvio',
      'raportti.kommentti': 'Kommentti',
      'raportti.lataa_tekstiraportti': 'Lataa tekstiraportti',
      'raportti.nayta_kommentit': 'Näytä kaikki kommentit',
      'raportti.otsikko': 'Raportti',
      'raportti.paivays': 'Päiväys',
      'raportti.palaa_arviointiin': 'Arvioi osaaminen',
      'raportti.tyyppi_raportti': 'Raportti',
      'raportti.tyyppi_tekstiraportti': 'Tekstiraportti',
      'raportti.valintojen_selitykset': 'Numeroiden selitykset:',
      'raportti.vastausprosentit': 'Vastausprosentit',
      'tallennus.kopioi_ohje': 'Valitse linkki ja kopioi se leikepöydälle painamalla:',
      'tallennus.laheta_sahkopostilla': 'Tai lähetä linkki sähköpostilla.',
      'tallennus.otsikko': 'Arvio tallennettu',
      'tallennus.sulje': 'Sulje',
      'tallennus.teksti': 'Arvio on nyt tallennettu. Alla olevasta linkistä löydät tekemäsi arviot.',
      'tutkinto.ei_loytynyt': 'Tutkintoja ei löytynyt',
      'tutkinto.eperusteet_linkki': 'Katso tutkinnon perusteet ePerusteet-järjestelmässä',
      'tutkinto.eperusteet_linkki_info': 'Tutkinnon perusteasiakirjasta näet, mistä pakollisista ja valinnaisista tutkinnon osista tutkinto muodostuu sekä tarkempaa tietoa tutkinnosta ja sen vaatimuksista.',
      'tutkinto.koulutustarjonta_linkki': 'Katso koulutuksen järjestäjät',
      'tutkinto.koulutustarjonta_linkki_info': 'Tahot, jotka järjestävät ammatillista peruskoulutusta tähän tutkintoon. Ammatillinen peruskoulutus on erityisesti nuorille suunniteltu tutkinnon suorittamistapa.',
      'tutkinto.nayttotutkinnonjarjestajat_linkki': 'Katso näyttötutkinnon järjestäjät',
      'tutkinto.nayttotutkinnonjarjestajat_linkki_info': 'Tahot, jotka järjestävät tätä tutkintoa näyttötutkintona. Näyttötutkinto on erityisesti aikuisille suunniteltu tutkinnon suorittamistapa.',
      'tutkinto.otsikko': 'Aloita etsimällä ja valitsemalla haluamasi tutkinto',
      'tutkinto.peruste_tyyppi_naytto': 'Näyttötutkinto',
      'tutkinto.peruste_tyyppi_ops': 'Peruskoulutus',
      'tutkinto.tyyppi': 'Tutkintotyyppi',
      'tutkinto.tyyppi_ammattitutkinto': 'Ammattitutkinto',
      'tutkinto.tyyppi_erikoisammattitutkinto': 'Erikoisammattitutkinto',
      'tutkinto.tyyppi_kaikki': 'Kaikki',
      'tutkinto.tyyppi_perustutkinto': 'Perustutkinto',
      'tutkinto.voimaantulevat': 'Näytä myös voimaantulevat',
      'tutkinto_osa.arvioi': 'Arvioi osaaminen',
      'tutkinto_osa.valitse': 'Valitse tutkinnon osat jotka haluat arvioida',
      'tutkinto_osa.valitse_tutkinto': 'Valitse tutkinto',
      'varmistus.peruuta': 'Peruuta',
      'yleiset.kielen_vaihto': 'På svenska',
      'yleiset.tallenna': 'Tallenna arviot',
      'yleiset.valitse_tutkinto': 'Valitse tutkinto'
    },
    sv: {
      'arviointi.arvioi_osaamisesi': 'Arvioi osaamisesi (sv)',
      'arviointi.arvioita_puuttuu': 'Et ole antanut arvioita kaikista ammattitaidoista! (sv)',
      'arviointi.asteikko1': 'En osaa (sv)',
      'arviointi.asteikko2': 'Osaan vähän (sv)',
      'arviointi.asteikko3': 'Osaan hyvin (sv)',
      'arviointi.asteikko4': 'Osaan erinomaisesti (sv)',
      'arviointi.eos': 'En osaa sanoa (sv)',
      'arviointi.raportti': 'Näytä raportti (sv)',
      'arviointi.tekstivastaus': 'Tekstivastaus (sv)',
      'arviointi.tekstivastaus_placeholder': 'Kirjoita vastauksesi tähän (sv)',
      'arviointi.valitse_osa': 'Valitse tutkinnon osat (sv)',
      'etusivu.opintoala': 'Ala (sv)',
      'etusivu.otsikko': 'Osaamisen tunnistaminen (sv)',
      'etusivu.teksti': 'Voit arvioida osaamistasi valitsemassasi ammatissa. Arviointi tehdään tutkinnoissa edellytettyjen ammattitaitovaatimusten perusteella, jotka on laadittu yhteistyössä työelämän kanssa. Tutkinnon suorittamisessa huomioidaan aiempi osaamisesi, joka voi olla hankittu esimerkiksi työssä, opinnoissa tai muussa toiminnassa. Kun hakeudut suorittamaan tutkintoa, koulutuksen järjestäjä selvittää aiemman osaamisen kanssasi.\n\nValitse tutkinto ja sen jälkeen ne tutkinnon osat, jotka haluaisit suorittaa. Sen jälkeen vastaa väittämiin. Saat vastauksista raportin, jonka voit tulostaa tai tallentaa. Henkilötietoja ei kysytä, raportti yksilöidään satunnaisella koodilla. Jos olet kiinnostunut suorittamaan ammatillisen perustutkinnon, ammattitutkinnon tai erikoisammattitutkinnon, ole yhteydessä näyttötutkinnon tai koulutuksen järjestäjiin, jotka näet linkkien kautta. (sv)',
      'etusivu.tutkinnon_nimi': 'Tutkinnon nimi (sv)',
      'etusivu.tutkinnon_nimi_placeholder': 'Kirjoita tutkinnon nimi tai nimen osa (sv)',
      'footer.ota_yhteytta': 'osaan.fi käyttöä koskevan palautteen voi lähettää sähköpostilla osoitteeseen (sv)',
      'footer.ota_yhteytta_email': 'aitu-tuki@oph.fi',
      'footer.otsikko': 'Palvelun tarjoaa Opetushallitus (sv)',
      'footer.rekisteriseloste': 'osaan.fi rekisteriselosteen voit lukea osoitteesta: (sv)',
      'footer.rekisteriseloste_url': 'http://osaan.fi/Rekisteriseloste%20Osaan%20sv.pdf',
      'lataa.palaa_etusivulle': 'Palaa etusivulle (sv)',
      'lataa.virhe': 'Virheellinen latauslinkki. (sv)',
      'osien-valinta.arvio_ladattu': '{{luotuaika}} luotu arviointisi on nyt ladattu. Voit jatkaa arviointiasi ja tallentaa uuden arvion. (sv)',
      'osien-valinta.arvio_ladattu_otsikko': 'Arvio on ladattu (sv)',
      'osien-valinta.arvioita_on': 'Valituille osille löytyy arvioita (sv)',
      'osien-valinta.eteenpain': 'Eteenpäin (sv)',
      'osien-valinta.pakolliset_osat': 'Pakolliset osat (sv)',
      'osien-valinta.poista_arviot': 'Poista arviot (sv)',
      'osien-valinta.poista_arviot_otsikko': 'Haluatko varmasti poistaa jo annetut arviot? (sv)',
      'osien-valinta.poista_arviot_varoitus': 'Arvioita ei voi palauttaa. (sv)',
      'osien-valinta.poisto-teksti': 'Jos haluat arvoida näiden osien osaamisesi uudestaan voit poistaa aiemmat arviosi (sv)',
      'osien-valinta.valinnaiset_osat': 'Valinnaiset osat (sv)',
      'osien-valinta.yhteiset_osat': 'Yhteiset osat (sv)',
      'polku.arvioi_osaaminen': 'Arvioi osaaminen (sv)',
      'polku.raportti': 'Raportti (sv)',
      'polku.valitse_tutkinnon_osat': 'Valitse tutkinnon osat (sv)',
      'polku.valitse_tutkinto': 'Valitse tutkinto (sv)',
      'raportti.ammattitaidon_kuvaus': 'Ammattitaidon kuvaus (sv)',
      'raportti.arvio': 'Arvio (sv)',
      'raportti.kommentti': 'Kommentti (sv)',
      'raportti.lataa_tekstiraportti': 'Lataa tekstiraportti (sv)',
      'raportti.nayta_kommentit': 'Näytä kaikki kommentit (sv)',
      'raportti.otsikko': 'Raportti (sv)',
      'raportti.paivays': 'Päiväys (sv)',
      'raportti.palaa_arviointiin': 'Arvioi osaaminen (sv)',
      'raportti.tyyppi_raportti': 'Raportti (sv)',
      'raportti.tyyppi_tekstiraportti': 'Tekstiraportti (sv)',
      'raportti.valintojen_selitykset': 'Numeroiden selitykset: (sv)',
      'raportti.vastausprosentit': 'Vastausprosentit (sv)',
      'tallennus.kopioi_ohje': 'Valitse linkki ja kopioi se leikepöydälle painamalla: (sv)',
      'tallennus.laheta_sahkopostilla': 'Tai lähetä linkki sähköpostilla. (sv)',
      'tallennus.otsikko': 'Arvio tallennettu',
      'tallennus.sulje': 'Sulje',
      'tallennus.teksti': 'Arvio on tallennettu. Voit nyt kopioida alla olevan linkin.',
      'tutkinto.ei_loytynyt': 'Tutkintoja ei löytynyt (sv)',
      'tutkinto.eperusteet_linkki': 'Katso tutkinnon perusteet ePerusteet-järjestelmässä (sv)',
      'tutkinto.eperusteet_linkki_info': 'Tutkinnon perusteasiakirjasta näet, mistä pakollisista ja valinnaisista tutkinnon osista tutkinto muodostuu sekä tarkempaa tietoa tutkinnosta ja sen vaatimuksista. (sv)',
      'tutkinto.koulutustarjonta_linkki': 'Katso koulutuksen järjestäjät (sv)',
      'tutkinto.koulutustarjonta_linkki_info': 'Tahot, jotka järjestävät ammatillista peruskoulutusta tähän tutkintoon. Ammatillinen peruskoulutus on erityisesti nuorille suunniteltu tutkinnon suorittamistapa. (sv)',
      'tutkinto.nayttotutkinnonjarjestajat_linkki': 'Katso näyttötutkinnon järjestäjät (sv)',
      'tutkinto.nayttotutkinnonjarjestajat_linkki_info': 'Tahot, jotka järjestävät tätä tutkintoa näyttötutkintona. Näyttötutkinto on erityisesti aikuisille suunniteltu tutkinnon suorittamistapa. (sv)',
      'tutkinto.otsikko': 'Aloita etsimällä ja valitsemalla haluamasi tutkinto (sv)',
      'tutkinto.peruste_tyyppi_naytto': 'Näyttötutkinto (sv)',
      'tutkinto.peruste_tyyppi_ops': 'Peruskoulutus (sv)',
      'tutkinto.tyyppi': 'Tutkintotyyppi (sv)',
      'tutkinto.tyyppi_ammattitutkinto': 'Ammattitutkinto (sv)',
      'tutkinto.tyyppi_erikoisammattitutkinto': 'Erikoisammattitutkinto (sv)',
      'tutkinto.tyyppi_kaikki': 'Kaikki (sv)',
      'tutkinto.tyyppi_perustutkinto': 'Perustutkinto (sv)',
      'tutkinto.voimaantulevat': 'Näytä myös voimaantulevat (sv)',
      'tutkinto_osa.arvioi': 'Arvioi osaaminen (sv)',
      'tutkinto_osa.valitse': 'Valitse tutkinnon osat jotka haluat arvioida (sv)',
      'tutkinto_osa.valitse_tutkinto': 'Valitse tutkinto (sv)',
      'varmistus.peruuta': 'Peruuta (sv)',
      'yleiset.kielen_vaihto': 'Suomeksi',
      'yleiset.tallenna': 'Tallenna arviot (sv)',
      'yleiset.valitse_tutkinto': 'Valitse tutkinto (sv)'
    }
  })

  .config(['$translateProvider', 'tekstit', function ($translateProvider, tekstit) {
    $translateProvider.translations('fi', tekstit.fi);
    $translateProvider.translations('sv', tekstit.sv);

    $translateProvider.use(localStorage.getItem('kieli') || 'fi');
  }])

  .factory('kieli', [function () {
    return localStorage.getItem('kieli') || 'fi';
  }])
;
