# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://github.com/fgrehm/vagrant-cachier#quick-start
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  vmbox = "CentOS-6.5-x86_64-v20140311.box"
  vmbox_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140311.box"

  # Kehitystyön tietokantapalvelin
  config.vm.define "osaan-db" do |db|
    db.vm.box = vmbox
    db.vm.box_url = vmbox_url

    db.vm.synced_folder "../env", "/env"
    if File.directory?("../../osaan.fi-dbdump")
      db.vm.synced_folder "../../osaan.fi-dbdump", "/dumps"
    end
    db.vm.provision "shell", inline: "cd /env && ./db-server.sh local 192.168.50.72 local/ssh/dev_id_rsa.pub"

    # local port 4567 -> vm port 5432
    db.vm.network "forwarded_port", host: 4567, guest: 5432
    db.vm.network "private_network", ip: "192.168.50.71"
  end

end
